name: inspect-runner
on: [push]

jobs:
  inspect-runner:
    runs-on: gcp-k8s-vllm-l4-solo

    steps:

      - name: check nvcc
        run: nvcc --version

      - name: check paths
        run: |
          echo "PATH=$PATH"
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
        shell: bash

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - uses: actions/checkout@v4

      - name: "⚙️ Install dependencies"
        id: install-deps
        run: pip3 install -U pip setuptools && pip3 install .[dev]

      - name: check torch cuda access
        if: ${{ !cancelled() && steps.install-deps.outcome == 'success' }}
        run: python3 -c "import torch; print(f'{torch.cuda.is_available()=}')"
