name: inspect-runner
on: [push]

jobs:
  inspect-runner:
    runs-on: gcp-k8s-vllm-l4-solo

    steps:
      - name: update env vars
        run: |
          echo "PATH=${PATH:+$PATH:}:/usr/local/cuda-12.4/lib64:/usr/local/nvidia/lib64" | tee -a "$GITHUB_ENV"
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/usr/local/cuda-12.4/lib64:/usr/local/nvidia/lib64" | tee -a "$GITHUB_ENV"
        shell: bash

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - uses: actions/checkout@v4
      - name: "⚙️ Install dependencies"
        run: pip3 install -U pip setuptools && pip3 install .[dev]

      - name: nvcc version
        run: nvcc --version

      - name: nvidia-smi
        if: ${{ !cancelled() }}
        run: nvidia-smi

      - name: install torch
        if: ${{ !cancelled() }}
        id: torch
        run: pip3 install torch

      - name: check torch cuda access
        if: ${{ !cancelled() && steps.torch.outcome == 'success' }}
        run: python3 -c "import torch; print(f'{torch.cuda.is_available()=}')"
